import {orientationAngles,angleLabel} from './orientation.mjs?v=9';
import {Receiver,decode} from './core.mjs';
import {rideStore,recordStore} from './storage.js?v=3';
import {calibrate,samplesFromCsv,validCalibration,calibratedCsv,setLevelReference,refineRideGyroBias,usesDeviceAxes} from './calibration.mjs?v=9';
import {createProfile,updateProfile,validProfile,exportProfiles as profileBackup,importProfiles as readProfileBackup} from './profiles.mjs?v=2';
import {RideWorkflow} from './ride-workflow.mjs';

const $=id=>document.getElementById(id),uuid=n=>`7b7e${n}-6f1d-4f35-9f55-42494b45434f`,enc=new TextEncoder();
const workflow=new RideWorkflow();
let device,command,statusChar,receiver,ride,operation=false,active=false,finishing=false,recording=false;
let statusWait=null,tail=Promise.resolve(),packetChain=Promise.resolve(),lastPacket=0,transfer=null;
let profiles=[],selectedProfile=null,legacyCalibration=null,setupTargetId=null;
const message=s=>$('status').textContent=s,text=v=>new TextDecoder().decode(v);
const profilesKey=()=>`bike-profiles:${device.id}`,selectedKey=()=>`selected-bike:${device.id}`,calibrationKey=()=>`calibration:${device.id}`;
const newId=()=>globalThis.crypto?.randomUUID?.()||`bike-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function calibrationMetrics(c){const d=c?.diagnostics;return d?`${d.samples} samples · gravity ${d.gravityMg.toFixed(0)} mg · acceleration noise ${d.accelRmsMg.toFixed(1)} mg · gyro noise ${d.gyroRmsDps.toFixed(1)} °/s`:'';}
function showSetupResult(kind,title,details){$('calibrationResult').className=`calibration-result ${kind}`;$('calibrationStatus').textContent=title;$('calibrationDetails').textContent=details||'';}
function profileCalibration(profile){return profile?{...structuredClone(profile.calibration),bikeProfileId:profile.id,bikeName:profile.name}:null;}
function renderProfile(){
 $('bikeSelect').innerHTML=profiles.length?profiles.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join(''):'<option value="">No saved bikes</option>';
 $('bikeSelect').value=selectedProfile?.id||'';$('profileCard').hidden=!selectedProfile;
 if(selectedProfile){
  $('profileName').textContent=selectedProfile.name;$('profilePitch').textContent=angleLabel(selectedProfile.mountPitch);$('profileRoll').textContent=angleLabel(selectedProfile.mountRoll);
  $('profileUpdated').textContent=new Date(selectedProfile.updatedAt).toLocaleDateString();$('profileQuality').textContent=`Saved mounting setup · ${calibrationMetrics(selectedProfile.calibration)}`;
  showSetupResult('pass',`${selectedProfile.name} is ready`,'This saved mounting setup will be copied into the next ride.');
 }else if(device?.gatt.connected)showSetupResult('idle','No bike selected','Add a bike once, then it will be available here for future rides.');
 controls();
}
async function persistProfiles(){await recordStore(profilesKey(),profiles);await recordStore(selectedKey(),selectedProfile?.id||null);}
async function chooseProfile(id,persist=true){selectedProfile=profiles.find(p=>p.id===id)||null;workflow.setCalibration(profileCalibration(selectedProfile));if(persist&&device)await recordStore(selectedKey(),selectedProfile?.id||null);renderProfile();}
function controls(){
 const connected=!!command&&!!device?.gatt.connected,locked=operation||active,settingUp=!$('setupPanel').hidden;
 $('connect').disabled=locked;$('connect').textContent=connected?'Disconnect':'Connect Bike Coach';
 $('addBike').disabled=!connected||locked;$('bikeSelect').disabled=!connected||locked||!profiles.length||settingUp;
 for(const id of ['updateBike','renameBike','deleteBike'])$(id).disabled=!connected||locked||!selectedProfile;
 $('beginSetup').disabled=!connected||locked;$('useExistingSetup').disabled=!connected||locked;$('cancelSetup').disabled=locked;
 $('start').disabled=!connected||locked||settingUp||!selectedProfile||!!workflow.pending;$('stop').disabled=!connected||locked;$('download').disabled=!connected||locked;
 $('small').disabled=locked;$('cancel').hidden=!active;$('analyze').disabled=locked;$('applyCalibration').hidden=!ride||validCalibration(ride.calibration)||!selectedProfile;$('applyCalibration').disabled=locked;
 $('exportProfiles').disabled=!connected||locked||!profiles.length;$('importProfiles').disabled=!connected||locked;
 $('startHelp').textContent=!connected?'Connect Bike Coach first.':!selectedProfile?'Add or choose a bike to enable Start ride.':workflow.pending?'Download the completed ride before starting another.':`Ready to record with ${selectedProfile.name}.`;
}
function openSetup(profile=null){setupTargetId=profile?.id||null;$('setupTitle').textContent=profile?`Update ${profile.name}`:'Add a bike';$('bikeName').value=profile?.name||'';$('bikeName').disabled=!!profile;$('useExistingSetup').hidden=!!profile||!usesDeviceAxes(legacyCalibration);$('setupPanel').hidden=false;controls();}
function closeSetup(){$('setupPanel').hidden=true;setupTargetId=null;controls();}

function write(s){const action=async()=>{if(!device?.gatt.connected||!command)throw Error('Bike Coach disconnected.');const b=enc.encode(s);if(command.properties.writeWithoutResponse&&command.writeValueWithoutResponse)await command.writeValueWithoutResponse(b);else if(command.writeValueWithResponse)await command.writeValueWithResponse(b);else await command.writeValue(b);};const p=tail.then(action);tail=p.catch(()=>{});return p;}
function rejectStatus(e){if(statusWait){const w=statusWait;statusWait=null;clearTimeout(w.timer);w.reject(e);}}
async function confirmed(cmd,prefixes){const response=new Promise((resolve,reject)=>{const timer=setTimeout(()=>{statusWait=null;reject(Error('Board did not confirm the command. Reconnect and try again.'));},5000);statusWait={resolve,reject,timer,prefixes};});response.catch(()=>{});try{await write(cmd);return await response;}catch(e){rejectStatus(e);throw e;}}
function onStatus(e){const s=text(e.target.value);if(statusWait&&(s.startsWith('ERR,')||statusWait.prefixes.some(p=>s.startsWith(p)))){const w=statusWait;statusWait=null;clearTimeout(w.timer);s.startsWith('ERR,')?w.reject(Error(s)):w.resolve(s);}if(s.startsWith('TRANSFER,')&&transfer)transfer.name=s.split(',')[2];else if(s==='TRANSFER_DONE')finishTransfer();else if(s.startsWith('ERR,')&&active)failTransfer(Error(s));else if(!operation&&!active&&s.startsWith('SAVED,'))message('Recording stopped. Ready to download.');}
function showRide(r){ride=r;$('result').hidden=false;$('progress').value=1;$('summary').textContent=`${r.name} · ${r.count.toLocaleString()} samples · ${(r.duration/1000).toFixed(1)} seconds${r.calibration?.bikeName?' · '+r.calibration.bikeName:''}`;$('saved').textContent=validCalibration(r.calibration)?`This ride includes the ${r.calibration.bikeName||'selected'} bike profile${r.calibration.rideBiasAdjusted?' and an automatic stationary gyro adjustment':''}.`:'No bike profile is attached. The analyzer will show raw sensor axes.';controls();}
function failTransfer(e){if(!transfer)return;const t=transfer;transfer=null;active=false;finishing=false;receiver=null;t.reject(e);controls();if(device?.gatt.connected)write('CANCEL_TRANSFER').catch(()=>{});}
function finishTransfer(){if(!transfer?.completed||!receiver?.done)return;const t=transfer;transfer=null;active=false;finishing=false;receiver=null;t.resolve(t.completed);controls();}
function download(kind,expectedName=null){if(active)return Promise.reject(Error('A download is already running.'));active=true;finishing=false;receiver=new Receiver($('small').checked?20:180);lastPacket=Date.now();$('progress').value=0;controls();message(kind==='setup'?'Downloading the bike setup…':'Downloading your ride…');return new Promise((resolve,reject)=>{transfer={kind,expectedName,name:null,resolve,reject,completed:null,waitingSince:0};write(`GET_LATEST,${receiver.limit},8`).catch(failTransfer);});}
function onPacket(e){const a=new Uint8Array(e.target.value.buffer,e.target.value.byteOffset,e.target.value.byteLength).slice(),owner=transfer;packetChain=packetChain.then(async()=>{if(!active||!receiver||transfer!==owner)return;lastPacket=Date.now();const result=receiver.accept(a);$('progress').value=receiver.size?receiver.offset/receiver.size:0;if(!receiver.done)message(`${owner.kind==='setup'?'Bike setup':'Ride'}: ${receiver.offset.toLocaleString()} of ${receiver.size.toLocaleString()} bytes`);if(result.done&&!finishing){finishing=true;const decoded=decode(receiver.bytes);if(!decoded.count)throw Error('This recording has no motion samples.');if(!owner.name){const s=text(await statusChar.readValue());if(s.startsWith('TRANSFER,'))owner.name=s.split(',')[2];}if(owner.expectedName&&owner.name!==owner.expectedName)throw Error('The board returned a different recording. Please reconnect and try again.');const completed={...decoded,name:owner.name||'ride.BIN',bytes:receiver.bytes.slice(),downloadedAt:new Date().toISOString()};if(owner.kind==='setup'){completed.calibration=calibrate(samplesFromCsv(decoded.csv),true);await recordStore(`calibration-sample:${device.id}`,completed);}else{const snapshot=workflow.forFile(completed.name);completed.calibration=snapshot?refineRideGyroBias(decoded.csv,snapshot):null;await rideStore(completed);showRide(completed);workflow.completed(completed.name);}if(transfer!==owner)return;owner.completed=completed;owner.waitingSince=Date.now();}if(result.ack)await write(result.ack);}).catch(failTransfer);}
setInterval(()=>{if(!active||!receiver||finishing)return;if(Date.now()-lastPacket>18000){failTransfer(Error('Download timed out. Reconnect and try again, using smaller packets if needed.'));return;}if(Date.now()-lastPacket>=100){const ack=receiver.flush();if(ack)write(ack).catch(failTransfer);}},100);
let checking=false;setInterval(async()=>{if(!active||!finishing||!transfer?.completed||checking)return;checking=true;const owner=transfer;try{if(text(await statusChar.readValue())==='TRANSFER_DONE')finishTransfer();else if(transfer===owner&&Date.now()-owner.waitingSince>18000)failTransfer(Error('Recording saved, but the board did not confirm completion. Reconnect before continuing.'));}catch(e){failTransfer(e);}finally{checking=false;}},1000);
async function run(action){if(operation||active)return;operation=true;controls();try{await action();}catch(e){message(e.message);}finally{operation=false;controls();}}

$('connect').onclick=async()=>{if(device?.gatt.connected){device.gatt.disconnect();return;}await run(async()=>{if(!navigator.bluetooth)throw Error('Open this page in Bluefy on your iPhone.');device=await navigator.bluetooth.requestDevice({filters:[{namePrefix:'BikeCoach'}],optionalServices:[uuid('1000')]});device.addEventListener('gattserverdisconnected',()=>{command=null;recording=false;profiles=[];selectedProfile=null;legacyCalibration=null;workflow.disconnected();rejectStatus(Error('Disconnected. Reconnect before continuing.'));failTransfer(Error('Disconnected during download. Reconnect and try again.'));closeSetup();renderProfile();showSetupResult('idle','Disconnected','Saved bike profiles remain on this phone.');message('Disconnected. Saved rides are still available.');$('connection').textContent='Not connected';controls();});try{const server=await device.gatt.connect(),service=await server.getPrimaryService(uuid('1000'));command=await service.getCharacteristic(uuid('1001'));statusChar=await service.getCharacteristic(uuid('1002'));const dataChar=await service.getCharacteristic(uuid('1003'));statusChar.addEventListener('characteristicvaluechanged',onStatus);await statusChar.startNotifications();dataChar.addEventListener('characteristicvaluechanged',onPacket);await dataChar.startNotifications();legacyCalibration=await recordStore(calibrationKey());const saved=await recordStore(profilesKey()),hadOldProfiles=Array.isArray(saved)&&saved.length>0;profiles=Array.isArray(saved)?saved.filter(validProfile):[];const selected=await recordStore(selectedKey());await chooseProfile(profiles.some(p=>p.id===selected)?selected:profiles[0]?.id||'',false);$('connection').textContent='Bike Coach connected';message(selectedProfile?`${selectedProfile.name} selected. You can start your ride.`:hadOldProfiles?'The direction calculation was corrected. Set up this bike once more.':'Connected. Add your first bike to continue.');if(!profiles.length)openSetup();}catch(e){device.gatt.disconnect();throw e;}});};

$('bikeSelect').onchange=()=>run(async()=>{await chooseProfile($('bikeSelect').value);message(`${selectedProfile.name} selected.`);});
$('addBike').onclick=()=>openSetup();$('updateBike').onclick=()=>openSetup(selectedProfile);$('cancelSetup').onclick=closeSetup;
async function saveProfileFromCalibration(name,result,targetId=null){
 if(!validCalibration(result))throw Error('Bike setup failed: '+result.reason);
 const angles=orientationAngles(result)||{pitch:0,roll:0},reference=setLevelReference(result);if(!reference)throw Error('The mounting direction could not be determined. Reposition the device and try again.');
 let profile;if(targetId){const old=profiles.find(p=>p.id===targetId);profile=updateProfile(old,{calibration:reference,mountPitch:angles.pitch,mountRoll:angles.roll});profiles=profiles.map(p=>p.id===targetId?profile:p);}else{profile=createProfile({id:newId(),name,calibration:reference,mountPitch:angles.pitch,mountRoll:angles.roll});profiles.push(profile);}
 selectedProfile=profile;workflow.setCalibration(profileCalibration(profile));await persistProfiles();await recordStore(calibrationKey(),reference);legacyCalibration=reference;closeSetup();renderProfile();showSetupResult('pass',`${profile.name} setup complete`,`${calibrationMetrics(reference)}. This mounting profile is saved on this phone.`);message(`${profile.name} is ready. Tap Start ride.`);
}
async function performBikeSetup(){
 const target=profiles.find(p=>p.id===setupTargetId),name=(target?.name||$('bikeName').value).trim();if(!name)throw Error('Enter a name for this bike.');
 showSetupResult('working','Setting up your bike','Hold the bike upright and completely still for six seconds.');
 await confirmed('STOP_RIDE',['SAVED,','IDLE']);const start=await confirmed('START_RIDE',['LOGGING,']);recording=true;const file=start.slice(8);let stopped=false;
 try{const deadline=Date.now()+6000;await new Promise((resolve,reject)=>{const timer=setInterval(()=>{if(!device?.gatt.connected){clearInterval(timer);reject(Error('Bike setup was interrupted.'));return;}const remaining=Math.ceil((deadline-Date.now())/1000);if(remaining<=0){clearInterval(timer);resolve();}else{showSetupResult('working','Setting up your bike',`Hold still — ${remaining} seconds remaining.`);message(`Hold still — ${remaining} seconds.`);}},100);});showSetupResult('working','Checking the setup','Downloading and checking the sensor sample…');const s=await confirmed('STOP_RIDE',['SAVED,']);recording=false;stopped=true;if(s.slice(6)!==file)throw Error('The setup recording changed. Reconnect and try again.');const sample=await download('setup',file);if(!validCalibration(sample.calibration)){showSetupResult('fail','Bike setup failed',`${sample.calibration.reason} ${calibrationMetrics(sample.calibration)}`);throw Error('Bike setup failed. Read the result above, then try again.');}await saveProfileFromCalibration(name,sample.calibration,target?.id||null);}finally{if(!stopped&&device?.gatt.connected){try{await confirmed('STOP_RIDE',['SAVED,','IDLE']);recording=false;}catch{}}}
}
$('beginSetup').onclick=()=>run(performBikeSetup);
$('useExistingSetup').onclick=()=>run(async()=>{const name=$('bikeName').value.trim();if(!name)throw Error('Enter a name for this bike.');await saveProfileFromCalibration(name,legacyCalibration);});
$('renameBike').onclick=()=>run(async()=>{const name=prompt('Bike name',selectedProfile.name);if(name===null)return;const changed=updateProfile(selectedProfile,{name});profiles=profiles.map(p=>p.id===changed.id?changed:p);selectedProfile=changed;workflow.setCalibration(profileCalibration(changed));await persistProfiles();renderProfile();message(`Renamed to ${changed.name}.`);});
$('deleteBike').onclick=()=>run(async()=>{if(!confirm(`Delete ${selectedProfile.name}?`))return;profiles=profiles.filter(p=>p.id!==selectedProfile.id);selectedProfile=profiles[0]||null;workflow.setCalibration(profileCalibration(selectedProfile));await persistProfiles();renderProfile();message(selectedProfile?`${selectedProfile.name} selected.`:'Bike deleted. Add a bike to start a ride.');});

$('start').onclick=()=>run(async()=>{if(!selectedProfile)throw Error('Choose a bike before starting.');if(workflow.pending)throw Error('Download your current ride before starting another.');workflow.setCalibration(profileCalibration(selectedProfile));await confirmed('STOP_RIDE',['SAVED,','IDLE']);const s=await confirmed('START_RIDE',['LOGGING,']);workflow.start(s.slice(8));recording=true;message(`Recording with ${selectedProfile.name}. You can move immediately.`);});
$('stop').onclick=()=>run(async()=>{const s=await confirmed('STOP_RIDE',['SAVED,','IDLE']);recording=false;if(s.startsWith('SAVED,'))workflow.stop(s.slice(6));message('Ride stopped. Tap Download latest ride.');});
$('download').onclick=()=>run(async()=>{const r=await download('ride',workflow.pending?.stopped?workflow.pending.name:null);message(validCalibration(r.calibration)?`Download complete with ${r.calibration.bikeName||'bike'} profile.`:'Download complete. No bike profile was linked to this ride.');});
$('cancel').onclick=()=>failTransfer(Error('Download cancelled. The original stays on the board.'));
$('applyCalibration').onclick=()=>run(async()=>{if(!ride||!selectedProfile)return;const r={...ride,calibration:profileCalibration(selectedProfile)};await rideStore(r);showRide(r);message(`${selectedProfile.name} profile attached to this ride.`);});
$('analyze').onclick=()=>location.href='analyzer.html?v=7&latest=1';
function save(csv){if(!ride)return;const data=csv?calibratedCsv(ride.csv,ride.calibration):ride.bytes,url=URL.createObjectURL(new Blob([data],{type:csv?'text/csv':'application/octet-stream'})),a=document.createElement('a');a.href=url;a.download=ride.name.replace(/\.[^.]+$/,'')+(csv?'.csv':'.bin');a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
$('saveCsv').onclick=()=>save(true);$('saveBin').onclick=()=>save(false);
$('exportProfiles').onclick=()=>run(async()=>{const url=URL.createObjectURL(new Blob([profileBackup(profiles)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='BikeCoach-bike-profiles.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);message('Bike profile backup prepared. Save it to Files.');});
$('importProfiles').onclick=()=>$('profileFile').click();
$('profileFile').onchange=e=>run(async()=>{const file=e.target.files?.[0];if(!file)return;const imported=readProfileBackup(await file.text()),merged=new Map(profiles.map(p=>[p.id,p]));for(const p of imported)merged.set(p.id,p);profiles=[...merged.values()];selectedProfile=imported[0];workflow.setCalibration(profileCalibration(selectedProfile));await persistProfiles();renderProfile();message(`${imported.length} bike profile${imported.length===1?'':'s'} imported.`);e.target.value='';});

rideStore().then(r=>{if(r)showRide(r);}).catch(()=>message('Allow website storage before downloading.'));renderProfile();controls();if(!navigator.bluetooth)message('For Bluetooth downloads on iPhone, open this page in Bluefy.');
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_ride_status',description:'Read connection, selected bike and ride status.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({connected:!!device?.gatt.connected,recording,downloading:active,selectedBike:selectedProfile?.name||null,bikeProfiles:profiles.map(p=>p.name),bytes:receiver?.offset||0,total:receiver?.size||0,savedRide:ride?{name:ride.name,samples:ride.count}:null})})).catch(()=>{});}catch{}}
