import {GuidedStart} from './guided-start.mjs';
import {Receiver,decode} from './core.mjs';
import {rideStore} from './storage.js';
const $=id=>document.getElementById(id),uuid=n=>`7b7e${n}-6f1d-4f35-9f55-42494b45434f`,enc=new TextEncoder();
let device,command,statusChar,dataChar,receiver,active=false,busy=false,tail=Promise.resolve(),lastPacket=0,ride,name='ride.BIN',finishing=false,waitingSince=0;
function message(s){$('status').textContent=s;}
function controls(){const ok=!!device?.gatt.connected;$('connect').disabled=busy||active||guided.active;$('connect').textContent=ok?'Disconnect':'Connect Bike Coach';for(const id of ['start','stop','download'])$(id).disabled=!ok||active||busy||guided.active;$('stop').disabled=!ok||active; $('cancel').hidden=!active;$('small').disabled=active;}
function write(s){const action=async()=>{if(!device?.gatt.connected||!command)throw Error('Bike Coach disconnected');const b=enc.encode(s);if(command.properties.writeWithoutResponse&&command.writeValueWithoutResponse)await command.writeValueWithoutResponse(b);else if(command.writeValueWithResponse)await command.writeValueWithResponse(b);else await command.writeValue(b);};const p=tail.then(action);tail=p.catch(()=>{});return p;}
let statusWait=null;
function waitStatus(prefixes){return new Promise((resolve,reject)=>{
  if(statusWait){clearTimeout(statusWait.timer);statusWait.reject(Error('Calibration interrupted.'));}
  const timer=setTimeout(()=>{statusWait=null;reject(Error('Board did not confirm recording. Reconnect and try again.'));},5000);
  statusWait={prefixes:Array.isArray(prefixes)?prefixes:[prefixes],resolve,reject,timer};
});}
function interruptCalibration(){guided.cancel();if(statusWait){clearTimeout(statusWait.timer);statusWait.reject(Error('Calibration interrupted. Start again.'));statusWait=null;}controls();}
const guided=new GuidedStart({send:write,waitStatus,show:message});
setInterval(()=>{const was=guided.active;guided.tick();if(was&&!guided.active)controls();},100);
function statusText(v){return new TextDecoder().decode(v);}
function onStatus(e){const s=statusText(e.target.value);if(statusWait&&(s.startsWith('ERR,')||statusWait.prefixes.some(p=>s.startsWith(p)))){const w=statusWait;statusWait=null;clearTimeout(w.timer);s.startsWith('ERR,')?w.reject(Error(s)):w.resolve(s);}if(guided.active&&!s.startsWith('ERR,'))return;if(s.startsWith('TRANSFER,')){const parts=s.split(',');name=parts[2]||'ride.BIN';}else if(s==='TRANSFER_DONE'){if(ride&&receiver?.done){active=false;message('Download complete. Your recording passed all integrity checks.');controls();}}else if(s==='TRANSFER_CANCELLED'){return;}else if(s.startsWith('ERR,')){const errors={STOP_RIDE_FIRST:'Tap Stop recording before downloading.',NO_COMPLETED_FILE_THIS_BOOT:'There is no completed ride since the board was powered on. Record a ride and stop it first.',SUBSCRIBE_1003:'Reconnect Bike Coach, then try the download again.',TRANSFER_TIMEOUT:'Download timed out. Reconnect and try again; use smaller packets if needed.',TRANSFER_BUSY:'A download is already running. Cancel it before starting another.'};fail(errors[s.slice(4)]||s.slice(4).replaceAll('_',' ').toLowerCase());}else if(!active){message(s.startsWith('SAVED,')?'Recording stopped. Ready to download.':s.startsWith('LOGGING,')?'Recording your ride…':s);}}
async function fail(e){const was=active;active=false;receiver=null;finishing=false;message(e instanceof Error?e.message:String(e));controls();if(was&&device?.gatt.connected)try{await write('CANCEL_TRANSFER')}catch{}}
function showRide(r){ride=r;$('result').hidden=false;$('summary').textContent=`${r.name} · ${r.count.toLocaleString()} samples · ${(r.duration/1000).toFixed(1)} seconds`;$('progress').value=1;}
let packetChain=Promise.resolve();
function onPacket(e){const a=new Uint8Array(e.target.value.buffer,e.target.value.byteOffset,e.target.value.byteLength).slice();packetChain=packetChain.then(async()=>{if(!active||!receiver)return;lastPacket=Date.now();const result=receiver.accept(a);$('progress').value=receiver.size?receiver.offset/receiver.size:0;if(!receiver.done)message(`Downloading… ${receiver.offset.toLocaleString()} of ${receiver.size.toLocaleString()} bytes`);if(result.done&&!finishing){finishing=true;const decoded=decode(receiver.bytes);if(!decoded.count)throw Error('This recording has no motion samples');const completed={...decoded,name,bytes:receiver.bytes.slice(),downloadedAt:new Date().toISOString()};await rideStore(completed);showRide(completed);message('Recording saved on this device. Confirming completion…');waitingSince=Date.now();}if(result.ack)await write(result.ack);}).catch(fail);}
$('connect').onclick=async()=>{if(device?.gatt.connected){device.gatt.disconnect();return;}busy=true;controls();try{if(!navigator.bluetooth)throw Error('Open this page in Bluefy on your iPhone to connect by Bluetooth.');device=await navigator.bluetooth.requestDevice({filters:[{namePrefix:'BikeCoach'}],optionalServices:[uuid('1000')]});device.addEventListener('gattserverdisconnected',()=>{command=null;busy=false;interruptCalibration();if(active)fail('Connection lost. Reconnect and download again.');else{message('Disconnected.');controls();}$('connection').textContent='Not connected';});const server=await device.gatt.connect(),service=await server.getPrimaryService(uuid('1000'));command=await service.getCharacteristic(uuid('1001'));statusChar=await service.getCharacteristic(uuid('1002'));dataChar=await service.getCharacteristic(uuid('1003'));statusChar.addEventListener('characteristicvaluechanged',onStatus);await statusChar.startNotifications();dataChar.addEventListener('characteristicvaluechanged',onPacket);await dataChar.startNotifications();$('connection').textContent='Bike Coach connected';message('Connected. Stop recording, then download your latest ride.');}catch(e){device?.gatt.disconnect();message(e.message);}finally{busy=false;controls();}};
async function simple(s){busy=true;controls();try{await write(s)}catch(e){message(e.message)}finally{busy=false;controls()}}
$('start').onclick=async()=>{if(guided.active||busy||active)return;const p=guided.start();controls();try{await p;}catch(e){message(e.message);}finally{controls();}};
$('stop').onclick=()=>{interruptCalibration();return simple('STOP_RIDE');};
$('download').onclick=async()=>{if(active)return;active=true;finishing=false;waitingSince=0;name='ride.BIN';receiver=new Receiver($('small').checked?20:180);lastPacket=Date.now();$('progress').value=0;controls();message('Requesting latest completed ride…');try{await write(`GET_LATEST,${receiver.limit},8`)}catch(e){fail(e)}};
$('cancel').onclick=()=>fail('Download cancelled. Your original recording is still on the board.');
setInterval(()=>{if(!active||!receiver||finishing)return;if(Date.now()-lastPacket>18000){fail('Download stopped responding. Reconnect and try again, using smaller packets if needed.');return;}if(Date.now()-lastPacket>=100){const ack=receiver.flush();if(ack)write(ack).catch(fail);}},100);
let checking=false;setInterval(async()=>{if(!active||!finishing||checking)return;checking=true;try{const s=statusText(await statusChar.readValue());if(s==='TRANSFER_DONE'){active=false;message('Download complete. Your recording passed all integrity checks.');controls();}else if(Date.now()-waitingSince>18000){active=false;message('Recording saved and verified. The board did not confirm completion; you can still analyze your ride.');controls();await write('CANCEL_TRANSFER');}}catch(e){fail(e)}finally{checking=false}},1000);
$('analyze').onclick=()=>location.href='analyzer.html?latest=1';
function save(csv){if(!ride)return;const blob=new Blob([csv?ride.csv:ride.bytes],{type:csv?'text/csv':'application/octet-stream'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=ride.name.replace(/\.[^.]+$/,'')+(csv?'.csv':'.bin');a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
$('saveCsv').onclick=()=>save(true);$('saveBin').onclick=()=>save(false);
rideStore().then(r=>{if(r)showRide(r)}).catch(()=>message('Local storage is unavailable. Allow website storage in this browser before downloading.'));
if(!navigator.bluetooth)message('For Bluetooth downloads on iPhone, open this page in Bluefy. The analyzer works without Bluetooth.');
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_ride_status',description:'Read connection, transfer progress and saved ride information.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({connected:!!device?.gatt.connected,downloading:active,bytes:receiver?.offset||0,total:receiver?.size||0,savedRide:ride?{name:ride.name,samples:ride.count,durationMs:ride.duration}:null})})).catch(()=>{});}catch{}}
