export function crc32(a){let c=0xffffffff;for(const b of a){c^=b;for(let j=0;j<8;j++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^0xffffffff)>>>0}
const eq=(a,b)=>a.length===b.length&&a.every((v,i)=>v===b[i]);
export class Receiver{
 constructor(limit=180){this.limit=limit;this.next=0;this.offset=0;this.history=new Map();this.done=false;this.pending=0;}
 accept(a){const v=new DataView(a.buffer,a.byteOffset,a.byteLength);if(a.length<12||a.length!==12+a[11]||a.length>this.limit)throw Error('Invalid Bluetooth packet length');const kind=a[0],id=v.getUint16(1,true),seq=v.getUint32(3,true),off=v.getUint32(7,true),p=a.subarray(12);if(!id)throw Error('Invalid transfer ID');
 if(!this.next){if(kind!==1||seq||off||p.length!==7||p[4]!==2||p[5]!==this.limit||p[6]!==8)throw Error('Unsupported transfer header');this.size=v.getUint32(12,true);if(this.size>64*1024*1024)throw Error('Recording is too large for this page');this.id=id;this.bytes=new Uint8Array(this.size);}
 else if(id!==this.id)throw Error('Transfer ID changed');
 const ack=()=>`ACK,${this.id},${this.next-1}`;
 if(seq<this.next){const prior=this.history.get(seq);if(!prior||!eq(prior,a))throw Error('Changed or stale repeated packet');return {ack:ack(),duplicate:true};}
 if(seq>this.next){if(seq>=this.next+8)throw Error('Packet outside transfer window');return {ack:ack()};}
 if(off!==this.offset)throw Error('Recording byte position does not match');
 if(seq){if(this.done)throw Error('Data after completion');if(kind===2){if(!p.length||this.offset+p.length>this.size)throw Error('Invalid recording length');this.bytes.set(p,this.offset);this.offset+=p.length;this.pending++;}else if(kind===3){if(p.length!==4||this.offset!==this.size||crc32(this.bytes)!==v.getUint32(12,true))throw Error('Recording integrity check failed');this.done=true;}else throw Error('Unexpected packet');}
 this.history.set(seq,a.slice());if(this.history.size>8)this.history.delete(this.history.keys().next().value);this.next++;if(kind!==2||this.pending>=8){this.pending=0;return {ack:ack(),done:this.done};}return {};
 }
 flush(){if(!this.pending)return null;this.pending=0;return `ACK,${this.id},${this.next-1}`;}
}
export function decode(a){const v=new DataView(a.buffer,a.byteOffset,a.byteLength),u=o=>v.getUint32(o,true),txt=(s,e)=>String.fromCharCode(...a.subarray(s,e));if(a.length<48||txt(0,4)!=='BCB1'||a[4]!==1||a[5]!==32||a[6]!==28||a[7]!==25||u(8)!==40000||a.slice(20,28).some(Boolean)||u(28)!==crc32(a.subarray(0,28)))throw Error('Unsupported or damaged recording header');const end=a.length-16,count=u(end+4),duration=u(end+12);if(txt(end,end+4)!=='BEND'||count*28!==end-32||u(end+8)!==crc32(a.subarray(32,end)))throw Error('Recording is incomplete or damaged');let year=v.getUint16(12,true),d=new Date(0);d.setUTCFullYear(year,a[14]-1,a[15]);d.setUTCHours(a[16],a[17],a[18],a[19]*10);let valid=year>=1&&year<=9999&&a[19]<100&&d.getUTCFullYear()===year&&d.getUTCMonth()===a[14]-1&&d.getUTCDate()===a[15]&&d.getUTCHours()===a[16]&&d.getUTCMinutes()===a[17]&&d.getUTCSeconds()===a[18];let previous=null;const lines=['rtcDate,rtcTime,aX,aY,aZ,gX,gY,gZ,mX,mY,mZ,imu_degC,output_Hz,elapsed_ms,mag_status1,mag_status2'];const pad=x=>String(x).padStart(2,'0');for(let o=32;o<end;o+=28){const elapsed=u(o),scale=a[o+24];if(scale>15||a[o+27]||elapsed>duration||(previous!==null&&elapsed<previous))throw Error('Invalid recording timestamps');const raw=Array.from({length:10},(_,i)=>v.getInt16(o+4+i*2,true));const t=new Date(d.getTime()+elapsed),date=valid?`${pad(t.getUTCMonth()+1)}/${pad(t.getUTCDate())}/${t.getUTCFullYear()}`:'',time=valid?`${pad(t.getUTCHours())}:${pad(t.getUTCMinutes())}:${pad(t.getUTCSeconds())}.${String(t.getUTCMilliseconds()).padStart(3,'0')}`:'';lines.push([date,time,...raw.slice(0,3).map(x=>x/[16.384,8.192,4.096,2.048][scale&3]),...raw.slice(3,6).map(x=>x/[131,65.5,32.8,16.4][scale>>2]),...raw.slice(6,9).map(x=>x*.15),(raw[9]-21)/333.87+21,previous!==null&&elapsed>previous?1000/(elapsed-previous):0,elapsed,a[o+25],a[o+26]].join(','));previous=elapsed;}return {csv:lines.join('\r\n')+'\r\n',count,duration};}
